/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AnimIronIcon {
    'animation': string;
    'circle': string;
    'icon': string;
  }
}

declare global {


  interface HTMLAnimIronIconElement extends Components.AnimIronIcon, HTMLStencilElement {}
  var HTMLAnimIronIconElement: {
    prototype: HTMLAnimIronIconElement;
    new (): HTMLAnimIronIconElement;
  };
  interface HTMLElementTagNameMap {
    'anim-iron-icon': HTMLAnimIronIconElement;
  }
}

declare namespace LocalJSX {
  interface AnimIronIcon extends JSXBase.HTMLAttributes<HTMLAnimIronIconElement> {
    'animation'?: string;
    'circle'?: string;
    'icon'?: string;
  }

  interface IntrinsicElements {
    'anim-iron-icon': AnimIronIcon;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


